version: "3.1"
services:
  scheduler:
    environment:
      - DATABRICKS_HOST=${DATABRICKS_HOST}
      - DATABRICKS_TOKEN=${DATABRICKS_TOKEN}
      - OPENLINEAGE_DISABLED=true 
      - AIRFLOW__OPENLINEAGE__DISABLED=true
      - AIRFLOW__LINEAGE__BACKEND=
  webserver:
    environment:
      - DATABRICKS_HOST=${DATABRICKS_HOST}
      - DATABRICKS_TOKEN=${DATABRICKS_TOKEN}
      - OPENLINEAGE_DISABLED=true
      - AIRFLOW__OPENLINEAGE__DISABLED=true
  worker:
    environment:
      - DATABRICKS_HOST=${DATABRICKS_HOST}
      - DATABRICKS_TOKEN=${DATABRICKS_TOKEN}
      - OPENLINEAGE_DISABLED=true
      - AIRFLOW__OPENLINEAGE__DISABLED=true